def ss(slug):
    return f"https://cdn.stocksnap.io/img-thumbs/960w/{slug}.jpg"

roofing = [
    ss("roof-tile_CHVBSJ555N"),
    ss("metal-roofing_WLATRYMBTU"),
    ss("house-roof_O7ZI0RF4MM"),
    ss("house-roof_URNIN5WJZP"),
    ss("house-roof_SQQD7NUGYO"),
    ss("house-roof_6ZANICCFI9"),
    ss("house-roof_EIWBYME50R"),
    ss("tile-roof_JKPSQFD1JX"),
    ss("roof-shingle_RIUJONCXNY"),
    ss("neighborhood-roof_QAPZB3ZMCW"),
    ss("aerial-house_IRL9YOSHFZ"),
    ss("architecture-house_S5XBPOGYIL"),
    ss("house-architecture_B4ESMQMFAM"),
    ss("house-neighborhood_U4OJOIJ2PB"),
    ss("modern-house_UIU7D31EDY"),
    ss("construction-worker_26F4EL6HIG"),
    ss("construction-worker_6B70C91911"),
    ss("construction-zone_6EAB6C3900"),
    ss("construction-plans_69YZFGFBSY"),
    ss("construction-tools_ZEYJ3YBEGP"),
    ss("level-construction_5HW69DS6ER"),
    ss("level-construction_ROG47AU0LS"),
    ss("farm-house_GSHIXNLN3K"),
    ss("exterior-wall_TUGC4JYFID"),
    ss("house-winter_O7Y8ZBW5HN"),
    ss("snow-winter_XIQNJAJFZO"),
    ss("modern-design_NNQVGVO2CR"),
    ss("modern-design_KQA30E4YCM"),
    ss("modern-design_EFXFRQX8ZR"),
    ss("modern-design_FRBIMQKMOZ"),
]

hvac = [
    ss("electrician-electricity_QJ55PI34SY"),
    ss("electrician-electricity_5OFPE51CY7"),
    ss("electrician-electricity_3A5FXM89OG"),
    ss("cables-wires_NTBTAJYIOK"),
    ss("pipe-water_WK8NGLULFI"),
    ss("pipe-line_TNTMA655QV"),
    ss("pipe-steel_ENMJFFF5V5"),
    ss("industrial-pipe_FM46LSJVCT"),
    ss("pipe-pipeline_KO662CNXTD"),
    ss("drainage-pipes_J7GDUQ3PHC"),
    ss("man-working_MGSIIACGM6"),
    ss("man-working_W57P75JBVL"),
    ss("workshop-wrench_O8DVPXYOIY"),
    ss("workshop-wrench_SM72VGLBBK"),
    ss("handyman-tools_CZ2V9D9RVP"),
    ss("handyman-tools_KNS7ZETDEF"),
    ss("handyman-tools_UUUGZVEU0R"),
    ss("industrial-parts_JCHI5DYDEG"),
    ss("ratchet-sockets_4RHOB6RC3S"),
    ss("construction-tools_QQVT4TRECF"),
    ss("construction-tools_EJZBX7UMTV"),
    ss("heat-glass_PSQ9M6C9N7"),
    ss("metal-abstract_3WDTUPJVX8"),
    ss("metal-abstract_HDPYTL8BJ3"),
    ss("industrial-concrete_TOWQ4GNEM9"),
    ss("industrial-concrete_MGQ4FGU9ZB"),
    ss("industrial-wall_HPNXDL5YZQ"),
    ss("structure-architecture_1J2IE3UE5B"),
    ss("automobile-repair_5VHL2NM8XJ"),
    ss("torch-welding_93EDC851A3"),
]

waterproofing = [
    ss("concrete-wall_FWJIWBGLB7"),
    ss("concrete-wall_VLMSF7OEQ0"),
    ss("concrete-wall_NLJESZLWIU"),
    ss("concrete-wall_70GQNT6XZM"),
    ss("industrial-concrete_TOWQ4GNEM9"),
    ss("industrial-concrete_MGQ4FGU9ZB"),
    ss("cracked-pavement_USYT9HQH6B"),
    ss("crack-road_EAH4L9KSFE"),
    ss("architecture-building_BTKIO9O6Y4"),
    ss("architecture-building_QJZVBK9JPC"),
    ss("architecture-building_3O76HRCJ9W"),
    ss("structure-building_0YVP86YTGO"),
    ss("building-structure_HFX5RBOUCR"),
    ss("dark-ground_ELZCOUA467"),
    ss("pipe-water_WK8NGLULFI"),
    ss("pipe-line_TNTMA655QV"),
    ss("pipe-steel_ENMJFFF5V5"),
    ss("drainage-pipes_J7GDUQ3PHC"),
    ss("pipe-pipeline_KO662CNXTD"),
    ss("industrial-pipe_FM46LSJVCT"),
    ss("modern-interior_YED8JWCWVB"),
    ss("building-exterior_KJCHJVFO9A"),
    ss("architecture-building_M0GR12B445"),
    ss("architecture-building_KZMREPI3IF"),
    ss("sewer-manhole_I3CVUTEPPS"),
    ss("washing-building_EKUPU3W8IO"),
    ss("industrial-wall_HPNXDL5YZQ"),
    ss("brick-wall_YR2IR5SYP5"),
    ss("brick-wall_C38SXT2PDA"),
    ss("architecture-building_P02O24GT9D"),
]

water_damage = [
    ss("water-droplets_3DQB34NZA7"),
    ss("water-droplets_7XFAYJTNXU"),
    ss("water-droplets_NE4EG37WRJ"),
    ss("water-droplets_YCPR5MQTRP"),
    ss("water-drop_COPRH306A9"),
    ss("water-drop_VLI4LYRHVL"),
    ss("flowing-water_F0AVOLNTOY"),
    ss("river-water_NK4UULG7KO"),
    ss("reflection-water_RPTE9LF9XP"),
    ss("chair-reflection_2D443SQ8GN"),
    ss("broken-glass_PXUWRHFNW4"),
    ss("cracked-pavement_USYT9HQH6B"),
    ss("crack-road_EAH4L9KSFE"),
    ss("dark-ground_ELZCOUA467"),
    ss("people-man_YFWK3Y0OZS"),
    ss("architecture-buildings_20MVZH0Y1N"),
    ss("man-working_MGSIIACGM6"),
    ss("man-working_W57P75JBVL"),
    ss("construction-worker_26F4EL6HIG"),
    ss("construction-worker_6B70C91911"),
    ss("workshop-wrench_O8DVPXYOIY"),
    ss("handyman-tools_CZ2V9D9RVP"),
    ss("concrete-wall_FWJIWBGLB7"),
    ss("building-structure_HFX5RBOUCR"),
    ss("architecture-building_GRQIKPV6TV"),
    ss("waterfalls-green_MO81GQRQOW"),
    ss("waterfall-iceland_AF9QPX5P5T"),
    ss("canyon-river_PMN3CTDC5X"),
    ss("coastal-landscape_GPZDMTKTHQ"),
    ss("ocean-water_J3ZGHIF8XT"),
]

niches = {
    "ROOFING": roofing,
    "HVAC": hvac,
    "WATERPROOFING": waterproofing,
    "WATER_DAMAGE": water_damage,
}

for niche, urls in niches.items():
    assert len(urls) == 30, f"{niche} has {len(urls)} URLs, expected 30"
    print(f"{niche} ({len(urls)} verified):")
    for url in urls:
        print(f'"{url}",')
    print()
